# Generated by Django 5.2.6 on 2025-09-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mic', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PriceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EQUITY', 'Equity'), ('ETF', 'ETF'), ('CRYPTO', 'Crypto')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('sector', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'active'], name='catalog_ins_kind_71ab6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32)),
                ('primary', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.exchange')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('contract_address', models.CharField(blank=True, max_length=128)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='catalog.instrument')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='catalog.network')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(max_length=3)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.instrument')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.listing')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.pricesource')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.token')),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['ticker'], name='catalog_lis_ticker_839b7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together={('exchange', 'ticker')},
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['symbol'], name='catalog_tok_symbol_1b9e2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('network', 'contract_address'), ('network', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['instrument', 'ts'], name='catalog_quo_instrum_e2317e_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['listing', 'ts'], name='catalog_quo_listing_89692b_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['token', 'ts'], name='catalog_quo_token_i_0c7ae8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('source', 'listing', 'token', 'ts')},
        ),
    ]
