# Generated by Django 5.2.6 on 2025-10-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='kind',
            field=models.CharField(choices=[('EQUITY', 'Equity'), ('ETF', 'ETF'), ('CRYPTO', 'Crypto'), ('COMMODITY', 'Commodity')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['source', 'ts'], name='catalog_quo_source__3935b5_idx'),
        ),
    ]
