# Generated by Django 5.2.6 on 2025-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_instrument_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='unit',
            field=models.CharField(blank=True, choices=[('UNIT', 'Unit'), ('SHARE', 'Share'), ('COIN', 'Coin'), ('BARREL', 'Barrel'), ('OUNCE', 'Ounce'), ('GRAM', 'Gram'), ('KILOGRAM', 'Kilogram'), ('LITER', 'Liter'), ('BUSHEL', 'Bushel'), ('POUND', 'Pound')], help_text='Unit for pricing/quantity (use codes like OUNCE, GRAM, SHARE, ...).', max_length=16),
        ),
    ]
