# Generated by Django 5.2.6 on 2025-10-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_instrument_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.instrument'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instrument__isnull', False), ('listing__isnull', True), ('token__isnull', True)), models.Q(('instrument__isnull', True), ('listing__isnull', False), ('token__isnull', True)), models.Q(('instrument__isnull', True), ('listing__isnull', True), ('token__isnull', False)), _connector='OR'), name='quote_exactly_one_target'),
        ),
    ]
